//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MonitorConsole.Models.Oracle
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OracleEventsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OracleEventsEntities object using the connection string found in the 'OracleEventsEntities' section of the application configuration file.
        /// </summary>
        public OracleEventsEntities() : base("name=OracleEventsEntities", "OracleEventsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OracleEventsEntities object.
        /// </summary>
        public OracleEventsEntities(string connectionString) : base(connectionString, "OracleEventsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OracleEventsEntities object.
        /// </summary>
        public OracleEventsEntities(EntityConnection connection) : base(connection, "OracleEventsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EVENTACTIONMAPPING> EVENTACTIONMAPPINGs
        {
            get
            {
                if ((_EVENTACTIONMAPPINGs == null))
                {
                    _EVENTACTIONMAPPINGs = base.CreateObjectSet<EVENTACTIONMAPPING>("EVENTACTIONMAPPINGs");
                }
                return _EVENTACTIONMAPPINGs;
            }
        }
        private ObjectSet<EVENTACTIONMAPPING> _EVENTACTIONMAPPINGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EVENTPROCESSTEMPLATE> EVENTPROCESSTEMPLATEs
        {
            get
            {
                if ((_EVENTPROCESSTEMPLATEs == null))
                {
                    _EVENTPROCESSTEMPLATEs = base.CreateObjectSet<EVENTPROCESSTEMPLATE>("EVENTPROCESSTEMPLATEs");
                }
                return _EVENTPROCESSTEMPLATEs;
            }
        }
        private ObjectSet<EVENTPROCESSTEMPLATE> _EVENTPROCESSTEMPLATEs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EVENTACTIONMAPPINGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEVENTACTIONMAPPINGs(EVENTACTIONMAPPING eVENTACTIONMAPPING)
        {
            base.AddObject("EVENTACTIONMAPPINGs", eVENTACTIONMAPPING);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EVENTPROCESSTEMPLATEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEVENTPROCESSTEMPLATEs(EVENTPROCESSTEMPLATE eVENTPROCESSTEMPLATE)
        {
            base.AddObject("EVENTPROCESSTEMPLATEs", eVENTPROCESSTEMPLATE);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OracleEventsModel", Name="EVENTACTIONMAPPING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EVENTACTIONMAPPING : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EVENTACTIONMAPPING object.
        /// </summary>
        /// <param name="eVENTACTIONMAPPINGID">Initial value of the EVENTACTIONMAPPINGID property.</param>
        /// <param name="eVENTID">Initial value of the EVENTID property.</param>
        /// <param name="sOURCETYPE">Initial value of the SOURCETYPE property.</param>
        /// <param name="sTATUS">Initial value of the STATUS property.</param>
        /// <param name="lASTMODIFIED">Initial value of the LASTMODIFIED property.</param>
        public static EVENTACTIONMAPPING CreateEVENTACTIONMAPPING(global::System.Int64 eVENTACTIONMAPPINGID, global::System.String eVENTID, global::System.String sOURCETYPE, global::System.String sTATUS, global::System.DateTime lASTMODIFIED)
        {
            EVENTACTIONMAPPING eVENTACTIONMAPPING = new EVENTACTIONMAPPING();
            eVENTACTIONMAPPING.EVENTACTIONMAPPINGID = eVENTACTIONMAPPINGID;
            eVENTACTIONMAPPING.EVENTID = eVENTID;
            eVENTACTIONMAPPING.SOURCETYPE = sOURCETYPE;
            eVENTACTIONMAPPING.STATUS = sTATUS;
            eVENTACTIONMAPPING.LASTMODIFIED = lASTMODIFIED;
            return eVENTACTIONMAPPING;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EVENTACTIONMAPPINGID
        {
            get
            {
                return _EVENTACTIONMAPPINGID;
            }
            set
            {
                if (_EVENTACTIONMAPPINGID != value)
                {
                    OnEVENTACTIONMAPPINGIDChanging(value);
                    ReportPropertyChanging("EVENTACTIONMAPPINGID");
                    _EVENTACTIONMAPPINGID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EVENTACTIONMAPPINGID");
                    OnEVENTACTIONMAPPINGIDChanged();
                }
            }
        }
        private global::System.Int64 _EVENTACTIONMAPPINGID;
        partial void OnEVENTACTIONMAPPINGIDChanging(global::System.Int64 value);
        partial void OnEVENTACTIONMAPPINGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EVENTPROCESSTEMPLATEID
        {
            get
            {
                return _EVENTPROCESSTEMPLATEID;
            }
            set
            {
                OnEVENTPROCESSTEMPLATEIDChanging(value);
                ReportPropertyChanging("EVENTPROCESSTEMPLATEID");
                _EVENTPROCESSTEMPLATEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EVENTPROCESSTEMPLATEID");
                OnEVENTPROCESSTEMPLATEIDChanged();
            }
        }
        private Nullable<global::System.Int64> _EVENTPROCESSTEMPLATEID;
        partial void OnEVENTPROCESSTEMPLATEIDChanging(Nullable<global::System.Int64> value);
        partial void OnEVENTPROCESSTEMPLATEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EVENTID
        {
            get
            {
                return _EVENTID;
            }
            set
            {
                OnEVENTIDChanging(value);
                ReportPropertyChanging("EVENTID");
                _EVENTID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EVENTID");
                OnEVENTIDChanged();
            }
        }
        private global::System.String _EVENTID;
        partial void OnEVENTIDChanging(global::System.String value);
        partial void OnEVENTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TRIGGERID
        {
            get
            {
                return _TRIGGERID;
            }
            set
            {
                OnTRIGGERIDChanging(value);
                ReportPropertyChanging("TRIGGERID");
                _TRIGGERID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TRIGGERID");
                OnTRIGGERIDChanged();
            }
        }
        private global::System.String _TRIGGERID;
        partial void OnTRIGGERIDChanging(global::System.String value);
        partial void OnTRIGGERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SOURCEID
        {
            get
            {
                return _SOURCEID;
            }
            set
            {
                OnSOURCEIDChanging(value);
                ReportPropertyChanging("SOURCEID");
                _SOURCEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOURCEID");
                OnSOURCEIDChanged();
            }
        }
        private Nullable<global::System.Int64> _SOURCEID;
        partial void OnSOURCEIDChanging(Nullable<global::System.Int64> value);
        partial void OnSOURCEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SOURCETYPE
        {
            get
            {
                return _SOURCETYPE;
            }
            set
            {
                OnSOURCETYPEChanging(value);
                ReportPropertyChanging("SOURCETYPE");
                _SOURCETYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SOURCETYPE");
                OnSOURCETYPEChanged();
            }
        }
        private global::System.String _SOURCETYPE;
        partial void OnSOURCETYPEChanging(global::System.String value);
        partial void OnSOURCETYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARAMETERTYPE
        {
            get
            {
                return _PARAMETERTYPE;
            }
            set
            {
                OnPARAMETERTYPEChanging(value);
                ReportPropertyChanging("PARAMETERTYPE");
                _PARAMETERTYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARAMETERTYPE");
                OnPARAMETERTYPEChanged();
            }
        }
        private global::System.String _PARAMETERTYPE;
        partial void OnPARAMETERTYPEChanging(global::System.String value);
        partial void OnPARAMETERTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USERSETUPPARAMVALUES
        {
            get
            {
                return _USERSETUPPARAMVALUES;
            }
            set
            {
                OnUSERSETUPPARAMVALUESChanging(value);
                ReportPropertyChanging("USERSETUPPARAMVALUES");
                _USERSETUPPARAMVALUES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USERSETUPPARAMVALUES");
                OnUSERSETUPPARAMVALUESChanged();
            }
        }
        private global::System.String _USERSETUPPARAMVALUES;
        partial void OnUSERSETUPPARAMVALUESChanging(global::System.String value);
        partial void OnUSERSETUPPARAMVALUESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private global::System.String _STATUS;
        partial void OnSTATUSChanging(global::System.String value);
        partial void OnSTATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TARGETID
        {
            get
            {
                return _TARGETID;
            }
            set
            {
                OnTARGETIDChanging(value);
                ReportPropertyChanging("TARGETID");
                _TARGETID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TARGETID");
                OnTARGETIDChanged();
            }
        }
        private Nullable<global::System.Int64> _TARGETID;
        partial void OnTARGETIDChanging(Nullable<global::System.Int64> value);
        partial void OnTARGETIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MODELID
        {
            get
            {
                return _MODELID;
            }
            set
            {
                OnMODELIDChanging(value);
                ReportPropertyChanging("MODELID");
                _MODELID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MODELID");
                OnMODELIDChanged();
            }
        }
        private Nullable<global::System.Int64> _MODELID;
        partial void OnMODELIDChanging(Nullable<global::System.Int64> value);
        partial void OnMODELIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTMODIFIED
        {
            get
            {
                return _LASTMODIFIED;
            }
            set
            {
                OnLASTMODIFIEDChanging(value);
                ReportPropertyChanging("LASTMODIFIED");
                _LASTMODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIED");
                OnLASTMODIFIEDChanged();
            }
        }
        private global::System.DateTime _LASTMODIFIED;
        partial void OnLASTMODIFIEDChanging(global::System.DateTime value);
        partial void OnLASTMODIFIEDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OracleEventsModel", Name="EVENTPROCESSTEMPLATE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EVENTPROCESSTEMPLATE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EVENTPROCESSTEMPLATE object.
        /// </summary>
        /// <param name="eVENTPROCESSTEMPLATEID">Initial value of the EVENTPROCESSTEMPLATEID property.</param>
        /// <param name="lASTMODIFIED">Initial value of the LASTMODIFIED property.</param>
        /// <param name="sTATUS">Initial value of the STATUS property.</param>
        public static EVENTPROCESSTEMPLATE CreateEVENTPROCESSTEMPLATE(global::System.Int64 eVENTPROCESSTEMPLATEID, global::System.DateTime lASTMODIFIED, global::System.String sTATUS)
        {
            EVENTPROCESSTEMPLATE eVENTPROCESSTEMPLATE = new EVENTPROCESSTEMPLATE();
            eVENTPROCESSTEMPLATE.EVENTPROCESSTEMPLATEID = eVENTPROCESSTEMPLATEID;
            eVENTPROCESSTEMPLATE.LASTMODIFIED = lASTMODIFIED;
            eVENTPROCESSTEMPLATE.STATUS = sTATUS;
            return eVENTPROCESSTEMPLATE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EVENTPROCESSTEMPLATEID
        {
            get
            {
                return _EVENTPROCESSTEMPLATEID;
            }
            set
            {
                if (_EVENTPROCESSTEMPLATEID != value)
                {
                    OnEVENTPROCESSTEMPLATEIDChanging(value);
                    ReportPropertyChanging("EVENTPROCESSTEMPLATEID");
                    _EVENTPROCESSTEMPLATEID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EVENTPROCESSTEMPLATEID");
                    OnEVENTPROCESSTEMPLATEIDChanged();
                }
            }
        }
        private global::System.Int64 _EVENTPROCESSTEMPLATEID;
        partial void OnEVENTPROCESSTEMPLATEIDChanging(global::System.Int64 value);
        partial void OnEVENTPROCESSTEMPLATEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEMPLATENAME
        {
            get
            {
                return _TEMPLATENAME;
            }
            set
            {
                OnTEMPLATENAMEChanging(value);
                ReportPropertyChanging("TEMPLATENAME");
                _TEMPLATENAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEMPLATENAME");
                OnTEMPLATENAMEChanged();
            }
        }
        private global::System.String _TEMPLATENAME;
        partial void OnTEMPLATENAMEChanging(global::System.String value);
        partial void OnTEMPLATENAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OPTIONALLEVEL
        {
            get
            {
                return _OPTIONALLEVEL;
            }
            set
            {
                OnOPTIONALLEVELChanging(value);
                ReportPropertyChanging("OPTIONALLEVEL");
                _OPTIONALLEVEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OPTIONALLEVEL");
                OnOPTIONALLEVELChanged();
            }
        }
        private Nullable<global::System.Decimal> _OPTIONALLEVEL;
        partial void OnOPTIONALLEVELChanging(Nullable<global::System.Decimal> value);
        partial void OnOPTIONALLEVELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LASTMODIFIED
        {
            get
            {
                return _LASTMODIFIED;
            }
            set
            {
                OnLASTMODIFIEDChanging(value);
                ReportPropertyChanging("LASTMODIFIED");
                _LASTMODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LASTMODIFIED");
                OnLASTMODIFIEDChanged();
            }
        }
        private global::System.DateTime _LASTMODIFIED;
        partial void OnLASTMODIFIEDChanging(global::System.DateTime value);
        partial void OnLASTMODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private global::System.String _STATUS;
        partial void OnSTATUSChanging(global::System.String value);
        partial void OnSTATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROCESSTEMPLATE
        {
            get
            {
                return _PROCESSTEMPLATE;
            }
            set
            {
                OnPROCESSTEMPLATEChanging(value);
                ReportPropertyChanging("PROCESSTEMPLATE");
                _PROCESSTEMPLATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROCESSTEMPLATE");
                OnPROCESSTEMPLATEChanged();
            }
        }
        private global::System.String _PROCESSTEMPLATE;
        partial void OnPROCESSTEMPLATEChanging(global::System.String value);
        partial void OnPROCESSTEMPLATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INITPARAMS
        {
            get
            {
                return _INITPARAMS;
            }
            set
            {
                OnINITPARAMSChanging(value);
                ReportPropertyChanging("INITPARAMS");
                _INITPARAMS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INITPARAMS");
                OnINITPARAMSChanged();
            }
        }
        private global::System.String _INITPARAMS;
        partial void OnINITPARAMSChanging(global::System.String value);
        partial void OnINITPARAMSChanged();

        #endregion
    
    }

    #endregion
    
}
